import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-gray-900 flex flex-col min-h-screen`}
        >
          <header className="fixed top-0 left-0 right-0 h-16 px-8 bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm border-b border-gray-200/80 dark:border-gray-800/80 flex items-center justify-between z-50">
            <div className="flex items-center space-x-4">
              <h1 className="text-xl font-bold bg-gradient-to-r from-blue-600 to-violet-600 bg-clip-text text-transparent">
                PDF Chat
              </h1>
            </div>
            <div className="flex items-center gap-3">
              <SignedOut>
                <SignInButton mode="modal">
                  <button className="px-4 py-2 text-sm text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white transition-colors">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton mode="modal">
                  <button className="px-4 py-2 text-sm text-white bg-gradient-to-r from-blue-600 to-violet-600 hover:from-blue-700 hover:to-violet-700 rounded-lg transition-all">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
            </div>
          </header>

          <SignedIn>
            <main className="flex-1 pt-16">
              <div className="max-w-7xl mx-auto w-full min-h-[calc(100vh-4rem)] p-8">
                {children}
              </div>
            </main>
          </SignedIn>
          
          <SignedOut>
            <main className="flex-1 flex items-center justify-center pt-16">
              <div className="text-center">
                <h2 className="text-2xl font-bold mb-4">Welcome to PDF Chat</h2>
                <p className="text-gray-600 dark:text-gray-400 mb-8">Please sign in to continue</p>
              </div>
            </main>
          </SignedOut>

          <footer className="mt-auto py-6 text-center text-sm text-gray-500 dark:text-gray-400 bg-white/80 dark:bg-gray-900/80 backdrop-blur-sm border-t border-gray-200/80 dark:border-gray-800/80">
            <p>© 2025 PDF Chat. All rights reserved.</p>
          </footer>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
